services:
  - type: web
    name: scholarship-finder-app
    env: node
    buildCommand: cd backend && npm install && cd .. && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        value: mongodb+srv://srisaiganeshdhanekula:9885422628@cluster0.hvo00rn.mongodb.net/scholarshipfinder?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: scholarship-finder-jwt-secret-2024-production-key-change-this
      - key: CORS_ORIGIN
        value: https://scholarship-finder-frontend.onrender.com 